---
application:
  name: "cryptocurrencyproject"
  project: "Crypto_project"
  organization: "QoveryCommunity"
  storage:
  - name: "Crypto_data"
    size: "500"
    type: "slow_hdd"
    mount_point: "/mnt/Crypto_data"
routers:
- name: "main-cryptocurrencyproject"
  routes:
  - application_name: "cryptocurrencyproject"
    paths:
    - "/*"
